### ISSUE TITLE
Bug:  Container Types

### ISSUE THREAD

**Issue by josegamboa** [pixijs/pixi-react#399] opened 2023-02-06 06:15 UTC
### Current Behavior

Hi, It seems like there is an issue with the example provided on the docs:

I have just created a project with :

`
import { BlurFilter } from 'pixi.js';
import { Stage, Container, Sprite, Text } from '@pixi/react';
import { useMemo } from 'react';

export const MyComponent = () =>
{
  const blurFilter = useMemo(() => new BlurFilter(4), []);

  return (
    <Stage>
      <Sprite
        image="https://pixijs.io/pixi-react/img/bunny.png"
        x={400}
        y={270}
        anchor={{ x: 0.5, y: 0.5 }}
      />

      <Container x={400} y={330}>
        <Text text="Hello World" anchor={{ x: 0.5, y: 0.5 }} filters={[blurFilter]} />
      </Container>
    </Stage>
  );
};

export default MyComponent;

`

And it is having a TypeScript issue with the Container component:

`Type '{ children: Element; x: number; y: number; }' is not assignable to type 'IntrinsicAttributes & Partial<Omit<Container<DisplayObject>, P | ReadonlyKeys<Container<DisplayObject>>> & WithPointLike<...>> & InteractionEvents & { ...; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Partial<Omit<Container<DisplayObject>, P | ReadonlyKeys<Container<DisplayObject>>> & WithPointLike<...>> & InteractionEvents & { ...; }'.ts(2322)`

If I do remove the container it works

### Expected Behavior

Compile example as it is on the  docs

### Steps to Reproduce

Create a new react typescript project and copy and paste the example from the docs

### Environment

- **`@pixi/react` version**: *e.g. 7.0.0*
- **`pixi.js` version**: *^7.1.2*
- **`React` version**: *e.g. 18.2.0*
- **`ReactDOM` version**: *e.g. 18.2.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Mac Ventura*

### Possible Solution

Update documentation

**Comment by baseten** [comment] 2023-02-06 15:46
Many thanks for posting the issue, I believe it's a dupe of https://github.com/pixijs/pixi-react/issues/350 - closing in favour of that issue.

**Closed by baseten** 2023-02-06 15:46 UTC
